### ISSUE TITLE
Lorenz data

### ISSUE THREAD

**Issue by tralala87** [baronefr/rhavok-analysis#8]
Hi. Why isn't the Lorenz Data csv generated through "data_generation.ipynb" used in the prediction ipynb notebook?

**Comment by baronefr** [comment]
Hello!

I think you are talking about `data/sb2017/Lorenz.csv`, is that right? 

As written in the *data* readme, folder `sb2017` contains data generated by the authors of the reference paper (S. Brunton et al. 2017). We do not want to use their data, so we are not using that file in particular.

Anyway, our data generation notebook (`data_generation.ipynb`) creates the file `data/attractors/Lorenz_timeseries.csv`. There is nothing wrong to use that data, of course. However, we have noticed that the performance of HAVOK crucially depends on the accuracy of the generated data, so we solved the Lorenz equations with a ODE45 integrator.

You find this more accurate generator in `data/data_lorenz_accurate.ipynb` and the corresponding dataset in `data/attractors/Lorenz_ext3000.npy` - which is indeed the file used in notebooks *h00* and *h01*. The parameters of the ODE45 integrator should be close to the ones used in MATLAB by S. Brunton et al.

I hope this answers to your question,

FB
